# Generated by Django 4.2.5 on 2023-10-17 19:33

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_payer_payee_user_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payer_payee',
            name='user',
        ),
        migrations.AddField(
            model_name='payer_payee',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_receiver', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='payer_payee',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payer', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default=accounts.models.default_profile_pic, upload_to='images/'),
        ),
    ]
