# Generated by Django 4.2.5 on 2023-10-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_payer_payee_user_payer_payee_payee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payer_payee',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='payer_payee',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_receiver', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_payer', to='accounts.user'),
        ),
    ]
