# Generated by Django 4.2.5 on 2023-10-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_payer_payee_payee_remove_payer_payee_payer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payer_payee',
        ),
    ]
