# Generated by Django 4.2.5 on 2023-10-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_payer_payee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payer',
            new_name='user',
        ),
    ]
